blueprint:
  name: Paralelo Virtual
  description: Acende/apaga todos os switches/lights do grupo simultaneamente
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de iluminação
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

trigger:
  - platform: state
    entity_id: !input entrada_switchs
    to:
      - "on"
      - "off"

condition:
  - condition: template
    value_template: "{{ trigger.to_state.context.parent_id is none }}"

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% else %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id: !input entrada_switchs

mode: single
