blueprint:
  name: Paralelo Virtual
  description: Acenda/Apaga todos os switchs/lights do grupo simultaneamente
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de Iluminação
      selector:
            entity:
              domain:
                - switch
                - light
              multiple: true

trigger:
  platform: state
  entity_id: !input entrada_switchs

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% elseif trigger.to_state.state == "off" %}
        homeassistant.turn_off
      {% endif %}
        target:
      entity_id: !input entrada_switchs
